//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/InputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMap"",
    ""maps"": [
        {
            ""name"": ""PlayerMove"",
            ""id"": ""358769f4-1e7e-4c4f-b7f4-83850e3f41b6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d067d194-7528-432a-af6d-dfd04b4496d9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""7b4c074e-2ed3-44ad-aff5-33c056a4bc82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""74cccb82-afd2-4458-947c-4f1860653735"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""492051fa-f9ed-43ad-aaf2-13bde407944e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0cf4bf07-9fb9-41db-bdc0-b1e2e0422bba"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6de2df37-b5fa-43b0-bef2-f56abc15c6cc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a5c018cb-3915-4c4c-a6ca-d953394608db"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9ac2bb72-8b92-4b12-97b2-f11a870f3ae2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cbbe8613-ecae-4757-93c8-870362a96adb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""48f9601b-bac1-44fc-9729-7a43aaec3675"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dde10fc-4e21-4984-9d41-fefdaa20d7c9"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70738879-915e-4c7c-8ee8-ab54849c0c8a"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerLook"",
            ""id"": ""bb5aa72e-0663-4f89-8bc8-72709f467872"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""5508039d-f15f-4732-8eda-942946f8e614"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c574a165-ed50-49c3-b307-c69f9cd5387c"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TankDrive"",
            ""id"": ""a2f70446-5942-44bd-b311-88ba3fccf78d"",
            ""actions"": [
                {
                    ""name"": ""Throttle"",
                    ""type"": ""Value"",
                    ""id"": ""1aca5be9-2e42-4598-9d58-253c73c6f360"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Value"",
                    ""id"": ""0c2dcde7-b296-4369-a115-d9789cd96acc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClutchLeft"",
                    ""type"": ""Value"",
                    ""id"": ""5f4cb91a-6344-4689-9f64-f015a575cb92"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClutchRight"",
                    ""type"": ""Value"",
                    ""id"": ""a71eab4e-a3b5-42b8-8d89-6c432f643074"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""730ab919-5753-4d13-87cb-732404f31452"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""efc201ef-7ed3-44a2-80b7-0bf5e86cecc4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a8897c50-d18b-4dc4-8967-0f7aa23c0925"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5b70cbd4-9f7a-498b-b5f2-868dd5afb084"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""03e55901-27e0-4293-8280-ccf2345b8520"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClutchLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""74f88843-800e-4dd9-848c-d4b3bd0bca3b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClutchLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b2b71546-7a8e-4d4f-a2e0-2070b538b3bf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClutchLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f4e2e578-ac2c-474f-9a2c-cfc0b4222964"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClutchRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3e586dd0-b454-4a13-8d13-6dec534f75c4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClutchRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4fb9a0c0-220e-4e91-b973-cc8be3d9be73"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClutchRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""PlayerSpecial"",
            ""id"": ""4c52e338-1a7c-4499-86ca-4d2c1686d9a6"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""4e00e768-3c63-4e8c-821a-66954e3bd53b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""0ee7a6a8-1536-4cb9-9be4-7ef4fee857c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9c4e715b-7d51-45e3-8566-f0a9321ea3b4"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""541b312a-1b44-4776-9937-8364d840d5fb"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TankSpecial"",
            ""id"": ""7e4835fb-5773-4fa0-97ea-c9a18581e8dc"",
            ""actions"": [
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""54ba5ebb-907c-473a-9ac1-57fdf1288d63"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""81f28a89-73a5-44ce-8317-5c602bc0cbca"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerGun"",
            ""id"": ""a6e0861e-ba99-4cfa-b2b6-50cc204fa259"",
            ""actions"": [
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""17554160-e22c-4414-ac2f-3d14b9a6cfd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""36b14872-807d-4c59-aa9f-c86f9ec10d90"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""e60940b0-55a8-40de-9f63-24ea7a5eb67e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CheckChamber"",
                    ""type"": ""Button"",
                    ""id"": ""22a8219e-c2a5-45b9-9dcd-6a7e7d3d76e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CheckClips"",
                    ""type"": ""Button"",
                    ""id"": ""78880e15-5645-4f62-ad5f-b915a92171ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bolt"",
                    ""type"": ""Button"",
                    ""id"": ""1efab203-0dd4-421d-92fc-2187ddcac002"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2d93dd5d-0303-4bd5-9e15-fe55666ae076"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""408b95b9-b8b5-4fbe-b189-c11ab809662c"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c692bdce-c16a-4bb0-aa18-8aaebe8c23d3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34056dd7-08a0-4b05-9f06-77beb870fa17"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CheckChamber"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68d080c4-9b33-4c65-a010-a00e85230966"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bolt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d7aa12e-6813-44c9-b5f1-9ccaf56f35d9"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CheckClips"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMove
        m_PlayerMove = asset.FindActionMap("PlayerMove", throwIfNotFound: true);
        m_PlayerMove_Move = m_PlayerMove.FindAction("Move", throwIfNotFound: true);
        m_PlayerMove_Jump = m_PlayerMove.FindAction("Jump", throwIfNotFound: true);
        m_PlayerMove_Sprint = m_PlayerMove.FindAction("Sprint", throwIfNotFound: true);
        m_PlayerMove_Crouch = m_PlayerMove.FindAction("Crouch", throwIfNotFound: true);
        // PlayerLook
        m_PlayerLook = asset.FindActionMap("PlayerLook", throwIfNotFound: true);
        m_PlayerLook_Move = m_PlayerLook.FindAction("Move", throwIfNotFound: true);
        // TankDrive
        m_TankDrive = asset.FindActionMap("TankDrive", throwIfNotFound: true);
        m_TankDrive_Throttle = m_TankDrive.FindAction("Throttle", throwIfNotFound: true);
        m_TankDrive_Brake = m_TankDrive.FindAction("Brake", throwIfNotFound: true);
        m_TankDrive_ClutchLeft = m_TankDrive.FindAction("ClutchLeft", throwIfNotFound: true);
        m_TankDrive_ClutchRight = m_TankDrive.FindAction("ClutchRight", throwIfNotFound: true);
        // PlayerSpecial
        m_PlayerSpecial = asset.FindActionMap("PlayerSpecial", throwIfNotFound: true);
        m_PlayerSpecial_Interact = m_PlayerSpecial.FindAction("Interact", throwIfNotFound: true);
        m_PlayerSpecial_Grab = m_PlayerSpecial.FindAction("Grab", throwIfNotFound: true);
        // TankSpecial
        m_TankSpecial = asset.FindActionMap("TankSpecial", throwIfNotFound: true);
        m_TankSpecial_Exit = m_TankSpecial.FindAction("Exit", throwIfNotFound: true);
        // PlayerGun
        m_PlayerGun = asset.FindActionMap("PlayerGun", throwIfNotFound: true);
        m_PlayerGun_Shoot = m_PlayerGun.FindAction("Shoot", throwIfNotFound: true);
        m_PlayerGun_Reload = m_PlayerGun.FindAction("Reload", throwIfNotFound: true);
        m_PlayerGun_Aim = m_PlayerGun.FindAction("Aim", throwIfNotFound: true);
        m_PlayerGun_CheckChamber = m_PlayerGun.FindAction("CheckChamber", throwIfNotFound: true);
        m_PlayerGun_CheckClips = m_PlayerGun.FindAction("CheckClips", throwIfNotFound: true);
        m_PlayerGun_Bolt = m_PlayerGun.FindAction("Bolt", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMove
    private readonly InputActionMap m_PlayerMove;
    private List<IPlayerMoveActions> m_PlayerMoveActionsCallbackInterfaces = new List<IPlayerMoveActions>();
    private readonly InputAction m_PlayerMove_Move;
    private readonly InputAction m_PlayerMove_Jump;
    private readonly InputAction m_PlayerMove_Sprint;
    private readonly InputAction m_PlayerMove_Crouch;
    public struct PlayerMoveActions
    {
        private @InputMap m_Wrapper;
        public PlayerMoveActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerMove_Move;
        public InputAction @Jump => m_Wrapper.m_PlayerMove_Jump;
        public InputAction @Sprint => m_Wrapper.m_PlayerMove_Sprint;
        public InputAction @Crouch => m_Wrapper.m_PlayerMove_Crouch;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMove; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMoveActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMoveActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMoveActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMoveActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
        }

        private void UnregisterCallbacks(IPlayerMoveActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
        }

        public void RemoveCallbacks(IPlayerMoveActions instance)
        {
            if (m_Wrapper.m_PlayerMoveActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMoveActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMoveActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMoveActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMoveActions @PlayerMove => new PlayerMoveActions(this);

    // PlayerLook
    private readonly InputActionMap m_PlayerLook;
    private List<IPlayerLookActions> m_PlayerLookActionsCallbackInterfaces = new List<IPlayerLookActions>();
    private readonly InputAction m_PlayerLook_Move;
    public struct PlayerLookActions
    {
        private @InputMap m_Wrapper;
        public PlayerLookActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerLook_Move;
        public InputActionMap Get() { return m_Wrapper.m_PlayerLook; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerLookActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerLookActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerLookActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerLookActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPlayerLookActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPlayerLookActions instance)
        {
            if (m_Wrapper.m_PlayerLookActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerLookActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerLookActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerLookActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerLookActions @PlayerLook => new PlayerLookActions(this);

    // TankDrive
    private readonly InputActionMap m_TankDrive;
    private List<ITankDriveActions> m_TankDriveActionsCallbackInterfaces = new List<ITankDriveActions>();
    private readonly InputAction m_TankDrive_Throttle;
    private readonly InputAction m_TankDrive_Brake;
    private readonly InputAction m_TankDrive_ClutchLeft;
    private readonly InputAction m_TankDrive_ClutchRight;
    public struct TankDriveActions
    {
        private @InputMap m_Wrapper;
        public TankDriveActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Throttle => m_Wrapper.m_TankDrive_Throttle;
        public InputAction @Brake => m_Wrapper.m_TankDrive_Brake;
        public InputAction @ClutchLeft => m_Wrapper.m_TankDrive_ClutchLeft;
        public InputAction @ClutchRight => m_Wrapper.m_TankDrive_ClutchRight;
        public InputActionMap Get() { return m_Wrapper.m_TankDrive; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TankDriveActions set) { return set.Get(); }
        public void AddCallbacks(ITankDriveActions instance)
        {
            if (instance == null || m_Wrapper.m_TankDriveActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TankDriveActionsCallbackInterfaces.Add(instance);
            @Throttle.started += instance.OnThrottle;
            @Throttle.performed += instance.OnThrottle;
            @Throttle.canceled += instance.OnThrottle;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
            @ClutchLeft.started += instance.OnClutchLeft;
            @ClutchLeft.performed += instance.OnClutchLeft;
            @ClutchLeft.canceled += instance.OnClutchLeft;
            @ClutchRight.started += instance.OnClutchRight;
            @ClutchRight.performed += instance.OnClutchRight;
            @ClutchRight.canceled += instance.OnClutchRight;
        }

        private void UnregisterCallbacks(ITankDriveActions instance)
        {
            @Throttle.started -= instance.OnThrottle;
            @Throttle.performed -= instance.OnThrottle;
            @Throttle.canceled -= instance.OnThrottle;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
            @ClutchLeft.started -= instance.OnClutchLeft;
            @ClutchLeft.performed -= instance.OnClutchLeft;
            @ClutchLeft.canceled -= instance.OnClutchLeft;
            @ClutchRight.started -= instance.OnClutchRight;
            @ClutchRight.performed -= instance.OnClutchRight;
            @ClutchRight.canceled -= instance.OnClutchRight;
        }

        public void RemoveCallbacks(ITankDriveActions instance)
        {
            if (m_Wrapper.m_TankDriveActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITankDriveActions instance)
        {
            foreach (var item in m_Wrapper.m_TankDriveActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TankDriveActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TankDriveActions @TankDrive => new TankDriveActions(this);

    // PlayerSpecial
    private readonly InputActionMap m_PlayerSpecial;
    private List<IPlayerSpecialActions> m_PlayerSpecialActionsCallbackInterfaces = new List<IPlayerSpecialActions>();
    private readonly InputAction m_PlayerSpecial_Interact;
    private readonly InputAction m_PlayerSpecial_Grab;
    public struct PlayerSpecialActions
    {
        private @InputMap m_Wrapper;
        public PlayerSpecialActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_PlayerSpecial_Interact;
        public InputAction @Grab => m_Wrapper.m_PlayerSpecial_Grab;
        public InputActionMap Get() { return m_Wrapper.m_PlayerSpecial; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerSpecialActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerSpecialActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerSpecialActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerSpecialActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Grab.started += instance.OnGrab;
            @Grab.performed += instance.OnGrab;
            @Grab.canceled += instance.OnGrab;
        }

        private void UnregisterCallbacks(IPlayerSpecialActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Grab.started -= instance.OnGrab;
            @Grab.performed -= instance.OnGrab;
            @Grab.canceled -= instance.OnGrab;
        }

        public void RemoveCallbacks(IPlayerSpecialActions instance)
        {
            if (m_Wrapper.m_PlayerSpecialActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerSpecialActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerSpecialActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerSpecialActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerSpecialActions @PlayerSpecial => new PlayerSpecialActions(this);

    // TankSpecial
    private readonly InputActionMap m_TankSpecial;
    private List<ITankSpecialActions> m_TankSpecialActionsCallbackInterfaces = new List<ITankSpecialActions>();
    private readonly InputAction m_TankSpecial_Exit;
    public struct TankSpecialActions
    {
        private @InputMap m_Wrapper;
        public TankSpecialActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Exit => m_Wrapper.m_TankSpecial_Exit;
        public InputActionMap Get() { return m_Wrapper.m_TankSpecial; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TankSpecialActions set) { return set.Get(); }
        public void AddCallbacks(ITankSpecialActions instance)
        {
            if (instance == null || m_Wrapper.m_TankSpecialActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TankSpecialActionsCallbackInterfaces.Add(instance);
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
        }

        private void UnregisterCallbacks(ITankSpecialActions instance)
        {
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
        }

        public void RemoveCallbacks(ITankSpecialActions instance)
        {
            if (m_Wrapper.m_TankSpecialActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITankSpecialActions instance)
        {
            foreach (var item in m_Wrapper.m_TankSpecialActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TankSpecialActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TankSpecialActions @TankSpecial => new TankSpecialActions(this);

    // PlayerGun
    private readonly InputActionMap m_PlayerGun;
    private List<IPlayerGunActions> m_PlayerGunActionsCallbackInterfaces = new List<IPlayerGunActions>();
    private readonly InputAction m_PlayerGun_Shoot;
    private readonly InputAction m_PlayerGun_Reload;
    private readonly InputAction m_PlayerGun_Aim;
    private readonly InputAction m_PlayerGun_CheckChamber;
    private readonly InputAction m_PlayerGun_CheckClips;
    private readonly InputAction m_PlayerGun_Bolt;
    public struct PlayerGunActions
    {
        private @InputMap m_Wrapper;
        public PlayerGunActions(@InputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shoot => m_Wrapper.m_PlayerGun_Shoot;
        public InputAction @Reload => m_Wrapper.m_PlayerGun_Reload;
        public InputAction @Aim => m_Wrapper.m_PlayerGun_Aim;
        public InputAction @CheckChamber => m_Wrapper.m_PlayerGun_CheckChamber;
        public InputAction @CheckClips => m_Wrapper.m_PlayerGun_CheckClips;
        public InputAction @Bolt => m_Wrapper.m_PlayerGun_Bolt;
        public InputActionMap Get() { return m_Wrapper.m_PlayerGun; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerGunActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerGunActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerGunActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerGunActionsCallbackInterfaces.Add(instance);
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @CheckChamber.started += instance.OnCheckChamber;
            @CheckChamber.performed += instance.OnCheckChamber;
            @CheckChamber.canceled += instance.OnCheckChamber;
            @CheckClips.started += instance.OnCheckClips;
            @CheckClips.performed += instance.OnCheckClips;
            @CheckClips.canceled += instance.OnCheckClips;
            @Bolt.started += instance.OnBolt;
            @Bolt.performed += instance.OnBolt;
            @Bolt.canceled += instance.OnBolt;
        }

        private void UnregisterCallbacks(IPlayerGunActions instance)
        {
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @CheckChamber.started -= instance.OnCheckChamber;
            @CheckChamber.performed -= instance.OnCheckChamber;
            @CheckChamber.canceled -= instance.OnCheckChamber;
            @CheckClips.started -= instance.OnCheckClips;
            @CheckClips.performed -= instance.OnCheckClips;
            @CheckClips.canceled -= instance.OnCheckClips;
            @Bolt.started -= instance.OnBolt;
            @Bolt.performed -= instance.OnBolt;
            @Bolt.canceled -= instance.OnBolt;
        }

        public void RemoveCallbacks(IPlayerGunActions instance)
        {
            if (m_Wrapper.m_PlayerGunActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerGunActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerGunActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerGunActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerGunActions @PlayerGun => new PlayerGunActions(this);
    public interface IPlayerMoveActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
    }
    public interface IPlayerLookActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface ITankDriveActions
    {
        void OnThrottle(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnClutchLeft(InputAction.CallbackContext context);
        void OnClutchRight(InputAction.CallbackContext context);
    }
    public interface IPlayerSpecialActions
    {
        void OnInteract(InputAction.CallbackContext context);
        void OnGrab(InputAction.CallbackContext context);
    }
    public interface ITankSpecialActions
    {
        void OnExit(InputAction.CallbackContext context);
    }
    public interface IPlayerGunActions
    {
        void OnShoot(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnCheckChamber(InputAction.CallbackContext context);
        void OnCheckClips(InputAction.CallbackContext context);
        void OnBolt(InputAction.CallbackContext context);
    }
}
